### ISSUE TITLE
pmauve crash on WSL with Fix

### ISSUE THREAD

**Issue by Talmonre** [moshi4/pyGenomeViz#13]
### Source Code

```python
#############
#Module code
#############

#!/root/miniconda3/envs/moshi/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from pygenomeviz.scripts.pmauve import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

### Error Content

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/moshi/bin/pgv-pmauve", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/pygenomeviz/scripts/pmauve.py", line 22, in main
    run(**args.__dict__)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/pygenomeviz/scripts/pmauve.py", line 159, in run
    gv.savefig(output_file, dpi=dpi)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/pygenomeviz/genomeviz.py", line 266, in savefig
    figure = self.plotfig(dpi=dpi)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/pygenomeviz/genomeviz.py", line 577, in plotfig
    figure: Figure = plt.figure(
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/pyplot.py", line 813, in figure
    manager = new_figure_manager(
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/pyplot.py", line 383, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3570, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3575, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1738, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
  File "/root/miniconda3/envs/moshi/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 483, in create_with_canvas
    window = tk.Tk(className="matplotlib")
  File "/root/miniconda3/envs/moshi/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "172.22.224.1:0"
```

### Fixed Source Code

```python
###########
#Fix
###########

import matplotlib
matplotlib.use('Agg')

###########
#New Module
###########

#!/root/miniconda3/envs/moshi/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
import matplotlib
matplotlib.use('Agg')

from pygenomeviz.scripts.pmauve import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by moshi4** [comment]
In a WSL2 environment that is not set up to connect to the display, you would probably get an error like `_tkinter.TclError: couldn't connect to display "172.22.224.1:0"`.

To solve this problem, you could use `matplotlib.use("Agg")` as in your modified code, but the following way may be easier.
1. Set backend to Agg in matplotlibrc file
2. Set MPLBACKEND environment variable to Agg

For more details, please refer to the following links.
https://matplotlib.org/stable/users/explain/backends.html

**Comment by Talmonre** [comment]
Thanks for getting back so quickly! I am loving your work! I thought I would post my work around for anyone who is also experiencing the same issue. Please feel free to close this or move it somewhere more useful.
