### ISSUE TITLE
run error pygenomeviz

### ISSUE THREAD

**Issue by sekhwal** [moshi4/pyGenomeViz#22]
I installed pygenomeviz in my conda environment but when I run the visualize.py, it does not exist. So, I downloaded it manually and ran it with the following command but it showed an error.

python visualize.py assembly/23.fasta assembly/233.fasta fastANI_results/fastani.out.visual out

ERROR:

Traceback (most recent call last):
  File "/Dropbox/sample_09212023/visualize.py", line 130, in <module>
    main()
  File "/Dropbox/sample_09212023/visualize.py", line 70, in main
    fig = gv.plotfig()
          ^^^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/pygenomeviz/genomeviz.py", line 535, in plotfig
    link.plot_link(ax, ylim)
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/pygenomeviz/link.py", line 156, in plot_link
    ax.add_patch(PathPatch(Path(verts, codes), **self._patch_kwargs()))
                                                 ^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/pygenomeviz/link.py", line 206, in _patch_kwargs
    default_kwargs = dict(fc=self.color, ec="grey", lw=lw, gid=self.gid)
                             ^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/pygenomeviz/link.py", line 98, in color
    nearly_white = to_nearly_white(color)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/pygenomeviz/link.py", line 95, in to_nearly_white
    cmap = colors.LinearSegmentedColormap.from_list("m", ("white", color))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/matplotlib/colors.py", line 1065, in from_list
    r, g, b, a = to_rgba_array(colors).T
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/fastANI_env/lib/python3.11/site-packages/matplotlib/colors.py", line 489, in to_rgba_array
    raise ValueError(f"{c!r} is not a valid color value.")
ValueError: 'white' is not a valid color value.

**Comment by moshi4** [comment]
Hi @sekhwal,

There seems to have been a change in the latest matplotlib v3.8.0 that affects the functionality of pyGenomeViz.
Try changing matplotlib from **v3.8.0** to **v3.7.3** and then rerun.

I plan to update pyGenomeViz to work with matplotlib v3.8.0 as well in the near future.

**Comment by moshi4** [comment]
### Note for myself

`to_rgba_array()` code changes in matplotlib v3.8.0 (Cause of error)

https://github.com/matplotlib/matplotlib/blob/39582424f8ce5e042e4e39eeac94893f222c9f8b/lib/matplotlib/colors.py#L438-L442

**Comment by moshi4** [comment]
I have released pyGenomeViz [v0.4.3](https://github.com/moshi4/pyGenomeViz/releases/tag/v0.4.3) which fixes bug when using matplotlib v3.8.0.

Please try updating to pyGenomeViz v0.4.3 and check if it works.
