### ISSUE TITLE
MMseqs RBH gui issue

### ISSUE THREAD

**Issue by iaindhay** [moshi4/pyGenomeViz#58]
I'm having an issue running the MMSeqs RBH in the gui (both in your demo and my local version 1.3.0). Both the MUMmer and BLAST comparisons seemingly work, but when i select the MMSeqs RBH option i get this in the gui:

```
File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/gui/app.py", line 449, in <module>
    gv, align_coords = plot.plot_by_gui_cfg(
                       ^^^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/gui/plot.py", line 114, in plot_by_gui_cfg
    align_coords = aligner.run()
                   ^^^^^^^^^^^^^
File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/align/tool/mmseqs.py", line 84, in run
    self.run_cmd(cmd, self._logger)
File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/align/tool/base.py", line 129, in run_cmd
    raise RuntimeError(f"Failed to run '{self.get_tool_name()}' aligner!!")
```

And this in my terminal window:

```
2024-08-15 12:04:16 | ERROR | Failed to run command below!!
2024-08-15 12:04:16 | ERROR | $ mmseqs easy-rbh '/tmp/tmpf4mpgto2/sample1.faa' '/tmp/tmpf4mpgto2/sample2.faa' '/tmp/tmpf4mpgto2/01_sample1_vs_sample2.tsv' /tmp/tmpf4mpgto2 --threads 32 -e 0.001 -v 0
2024-08-15 12:04:16 | ERROR | STDOUT:
2024-08-15 12:04:16 | ERROR | > Error: target createdb died
2024-08-15 12:04:16.392 Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/gui/app.py", line 449, in <module>
    gv, align_coords = plot.plot_by_gui_cfg(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/gui/plot.py", line 114, in plot_by_gui_cfg
    align_coords = aligner.run()
                   ^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/align/tool/mmseqs.py", line 84, in run
    self.run_cmd(cmd, self._logger)
  File "/opt/miniconda3/envs/pgv/lib/python3.12/site-packages/pygenomeviz/align/tool/base.py", line 129, in run_cmd
    raise RuntimeError(f"Failed to run '{self.get_tool_name()}' aligner!!")
RuntimeError: Failed to run 'MMseqs' aligner!!
```

Any Ideas?

**Comment by moshi4** [comment]
Maybe the CDS feature does not exist in your Genbank file, or the translation information does not exist in the CDS feature? In this case, the CDS protein fasta file to be compared in MMseqs will be empty, resulting in an error in MMseqs.

**Comment by iaindhay** [comment]
Ahh, your right. Thanks!
