### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by sajjadasaf** [moshi4/pyGenomeViz#6]
******************* Run Parameters ********************
seq_files:
  01. NC_028429.gbK
  02. NC_028523.gbK
outdir: pmauve_example
refid: 0
format: png
reuse: False
fig_width: 15
fig_track_height: 1.0
feature_track_ratio: 1.0
link_track_ratio: 5.0
tick_track_ratio: 1.0
track_labelsize: 20
tick_labelsize: 15
normal_link_color: grey
inverted_link_color: tomato
align_type: center
tick_style: bar
plotstyle: box
cmap: hsv
curve: False
dpi: 300
*********************************************************
Run progressiveMauve alignment.

Storing raw sequence at /tmp/rawseq127138.000
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure> >'
  what():  failed mapping file: Invalid argument
Aborted (core dumped)
Traceback (most recent call last):
  File "/home/sajjad/anaconda3/bin/pgv-pmauve", line 10, in <module>
    sys.exit(main())
  File "/home/sajjad/anaconda3/lib/python3.7/site-packages/pygenomeviz/scripts/pmauve.py", line 21, in main
    run(**args.__dict__)
  File "/home/sajjad/anaconda3/lib/python3.7/site-packages/pygenomeviz/scripts/pmauve.py", line 115, in run
    align_coords = pmauve.run()
  File "/home/sajjad/anaconda3/lib/python3.7/site-packages/pygenomeviz/align.py", line 472, in run
    return self.parse_pmauve_file(self.bbone_file)
  File "/home/sajjad/anaconda3/lib/python3.7/site-packages/pygenomeviz/align.py", line 489, in parse_pmauve_file
    header_row = next(reader)
StopIteration

**Comment by moshi4** [comment]
It appears that progressiveMauve is not correctly recognizing your Genbank file as Genbank format, possibly because your Genbank file extension is `*.gbK` (K is capitalized).

Could you modify `*.gbK` to `*.gbk` and try again?

**Comment by sajjadasaf** [comment]
I appreciate your prompt reply. Sorry, gbK, it was a typo. Thank you once again
