### ISSUE TITLE
File encoding errors on Windows

### ISSUE THREAD

**Issue by phyto** [moshi4/pyGenomeViz#63]
Hi Moshi4,
Just to let you know that I got an error message when trying to use 1.4.0 on Windows. I installed using `pip install pygenomeviz`, everything went fine, but I got the following error message when importing pygenomeviz : 
> Traceback (most recent call last):
  File "C:\Users\XXX\YYY.py", line 11, in <module>
   from pygenomeviz import GenomeViz
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygenomeviz\__init__.py", line 3, in <module>
    from pygenomeviz.genomeviz import GenomeViz
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygenomeviz\genomeviz.py", line 27, in <module>
    from pygenomeviz.viewer import setup_viewer_html
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygenomeviz\viewer\__init__.py", line 41, in <module>
    JS_CONTENTS = _concat_target_files_contents(_assets_files, ".js")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\site-packages\pygenomeviz\viewer\__init__.py", line 18, in _concat_target_files_contents
    contents += f.read() + "\n"
                ^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5743: character maps to <undefined>

I reverted to version 1.1.0 and everything is fine, but I thought it was better to let you know about this.
Thank you again for this great package!

**Comment by moshi4** [comment]
Try changing Python default encoding to UTF-8 by setting the environment variable `PYTHONUTF8=1`. 
This will probably fix the error, but it is a bit strange that there is a difference in behavior between v1.1.0 and v1.4.0.

**Comment by phyto** [comment]
Yes, this fixed the error. Thank you!
